# Generated by Django 5.1.6 on 2025-02-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["model"],
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ["name"],
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="capacity",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manufactured_cars",
                to="taxi.manufacturer",
            ),
        ),
    ]
