# Generated by Django 5.2.9 on 2025-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
