# Generated by Django 4.1 on 2024-02-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_options_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
    ]
