# Generated by Django 4.1 on 2025-09-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_drivers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("birth_year", models.IntegerField()),
                ("hobby", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "customers",
            },
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("manufacturer", "model")},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("username",)},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taxi.manufacturer"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
