from django.urls import path

from .views import (
    index,
    CarListView,
    CarCreateView,
    CarDetailView,
    CarUpdateView,
    CarDeleteView,
    DriverListView,
    DriverDetailView,
    DriverCreateView,
    DriverDeleteView,
    DriverLicenceUpdateView,
    ManufacturerListView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    driver_to_car,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list"
    ),
    path(
        "manufacturer/create/",
        ManufacturerCreateView.as_view(),
        name="create-manufacturer"
    ),
    path(
        "manufacturer/<int:pk>/update",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update",
    ),
    path(
        "manufacturer/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete",
    ),
    path(
        "cars/",
        CarListView.as_view(),
        name="car-list"),
    path(
        "cars/<int:pk>/",
        CarDetailView.as_view(),
        name="car-detail"
    ),
    path(
        "cars/create/",
        CarCreateView.as_view(),
        name="create-car"
    ),
    path(
        "cars/<int:pk>/update/",
        CarUpdateView.as_view(),
        name="car-update",
    ),
    path(
        "cars/<int:pk>/delete/",
        CarDeleteView.as_view(),
        name="car-delete",
    ),
    path(
        "drivers/",
        DriverListView.as_view(),
        name="driver-list",
    ),
    path(
        "drivers/create/",
        DriverCreateView.as_view(),
        name="driver-create",
    ),
    path(
        "drivers/<int:pk>/",
        DriverDetailView.as_view(),
        name="driver-detail"
    ),
    path(
        "drivers/<int:pk>/update-licence/",
        DriverLicenceUpdateView.as_view(),
        name="driver-update-licence",
    ),
    path(
        "drivers/<int:pk>/delete/",
        DriverDeleteView.as_view(),
        name="driver-delete",
    ),
    path(
        "cars/<int:pk>/link-unlink-driver/",
        driver_to_car,
        name="driver-to-car"
    ),
]

app_name = "taxi"
